"""empty message

Revision ID: 8c96122796d3
Revises: b00041fba059
Create Date: 2022-11-10 20:32:22.433937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c96122796d3'
down_revision = 'b00041fba059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['author'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'date_created')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'date_created')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###
