"""empty message

Revision ID: b00041fba059
Revises: 
Create Date: 2022-11-09 22:27:07.152209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00041fba059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=250), nullable=False),
    sa.Column('date', sa.VARCHAR(length=250), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=250), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=250), nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
